apiVersion: v1
kind: Service
metadata:
  name: yelb-ui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080 # Maps external 80 to new interal 8080 for nginx pod