apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-appserver
spec:
  template:
    spec:
      # Pod Level Security requirements
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: yelb-appserver
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault