apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelb-db
spec:
  template:
    spec:
      # Pod Level Security requirements
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: yelb-db
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false # postgres needs to write to /var/lib/postgres
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
            - name: pgrun
              mountPath: /var/run/postgresql
      volumes:
        - name: pgdata
          emptyDir: {}
        - name: pgrun
          emptyDir: {}